try:
    raise ValueError("Error in Values")
except ValueError:
    print("Error :")
    raise